const Terms = () => {
  return (
    <div className="min-h-screen py-20">
      <div className="container mx-auto px-4 max-w-4xl">
        <h1 className="text-4xl md:text-5xl font-bold mb-4">Terms of Service</h1>
        <p className="text-muted-foreground mb-12">Last updated: January 2025</p>

        <div className="prose prose-lg max-w-none space-y-8">
          <section>
            <p className="text-lg">
              Welcome to Audit-IQ ("we", "our", "the Service").
              By accessing or using Audit-IQ, you agree to these Terms of Service ("Terms").
              If you do not agree, please discontinue use of the platform.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">1. Service Description</h2>
            <p>
              Audit-IQ provides software tools that assist organisations in interpreting regulatory documents, 
              extracting obligations, summarising requirements, and organising evidence.
            </p>
            <p className="mt-2">
              Audit-IQ does not provide legal, regulatory, or compliance advice. All insights generated by the 
              platform should be independently reviewed by qualified professionals.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">2. Eligibility</h2>
            <p>You may use the Service only if:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>You are at least 18 years old, and</li>
              <li>You have the authority to enter into agreements on behalf of your organisation.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">3. Customer Responsibilities</h2>
            <p className="font-semibold">You agree to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Provide accurate information when creating an account or submitting documents.</li>
              <li>Upload only documents you have the legal right to process.</li>
              <li>Ensure that your use of the Service complies with applicable laws and internal policies.</li>
              <li>Keep login credentials confidential.</li>
            </ul>
            <p className="font-semibold mt-4">You must not:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Attempt to reverse engineer, copy, or misuse the service.</li>
              <li>Upload harmful, illegal, or malicious content.</li>
              <li>Use the Service to provide competing or unauthorised offerings.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">4. Document Handling</h2>
            <p>Uploaded documents may be temporarily processed to provide features such as:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Obligation extraction</li>
              <li>Requirement summarisation</li>
              <li>Evidence mapping</li>
            </ul>
            <p className="mt-2">Documents are handled securely and not used to train external AI models.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">5. Intellectual Property</h2>
            <p>Audit-IQ retains all rights, ownership, and intellectual property relating to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>The platform</li>
              <li>AI models</li>
              <li>User interface design</li>
              <li>Processing pipelines</li>
              <li>Generated insights</li>
            </ul>
            <p className="mt-2">Customers retain rights to their original uploaded documents.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">6. Limitation of Liability</h2>
            <p>Audit-IQ is provided on an "as-is" and "as-available" basis.</p>
            <p className="mt-2">We do not guarantee:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Accuracy of AI outputs</li>
              <li>Completeness of regulatory interpretation</li>
              <li>Suitability for audits or legal proceedings</li>
            </ul>
            <p className="mt-2">
              To the maximum extent permitted by law, Audit-IQ is not liable for indirect, incidental, or 
              consequential damages arising from use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">7. Termination</h2>
            <p>We may suspend or terminate access if:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>These Terms are violated</li>
              <li>The Service is misused</li>
              <li>Required by law</li>
            </ul>
            <p className="mt-2">You may stop using the platform at any time.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">8. Modifications</h2>
            <p>
              We may update these Terms periodically. Continued use of the Service after updates indicates acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">9. Governing Law</h2>
            <p>
              These Terms are governed by the laws of India unless otherwise agreed in a separate contract.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">10. Contact</h2>
            <p>
              For questions regarding these Terms:<br />
              📧 <a href="mailto:founder@audit-iq.com" className="text-accent hover:underline">founder@audit-iq.com</a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Terms;